# Generated by Django 3.2 on 2022-05-17 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
            options={
                'verbose_name': 'Баланс сервера',
                'verbose_name_plural': 'Баланс сервера',
            },
        ),
        migrations.CreateModel(
            name='ClientPurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=10, max_digits=19)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Баланс пользователя',
                'verbose_name_plural': 'Баланс пользователя',
            },
        ),
        migrations.CreateModel(
            name='ClientTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=10, max_digits=19)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('operations', models.CharField(choices=[('ADD', 'ADD'), ('DROP', 'DROP')], max_length=5, verbose_name='Тип операции')),
                ('purse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.clientpurse')),
            ],
            options={
                'verbose_name': 'Транзакция клиента',
                'verbose_name_plural': 'Транзакции клиента',
            },
        ),
        migrations.CreateModel(
            name='BankTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=10, max_digits=19)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('operations', models.CharField(choices=[('ADD', 'ADD'), ('DROP', 'DROP')], max_length=5, verbose_name='Тип операции')),
                ('purse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.clientpurse')),
            ],
            options={
                'verbose_name': 'Транзакция клиента',
                'verbose_name_plural': 'Транзакции клиента',
            },
        ),
    ]
