# Generated by Django 3.2 on 2022-05-17 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueClientTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Очередь транзакций',
                'verbose_name_plural': 'Очереди транзакций',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=10, max_digits=19)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('operations', models.CharField(choices=[('ADD', 'ADD'), ('DROP', 'DROP')], max_length=5, verbose_name='Тип операции')),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.queueclienttransactions')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.DeleteModel(
            name='BankAccountBalance',
        ),
        migrations.RemoveField(
            model_name='clienttransactions',
            name='purse',
        ),
        migrations.AddField(
            model_name='clientpurse',
            name='purse_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='BankTransactions',
        ),
        migrations.DeleteModel(
            name='ClientTransactions',
        ),
        migrations.AddField(
            model_name='queueclienttransactions',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.clientpurse'),
        ),
        migrations.AddField(
            model_name='queueclienttransactions',
            name='transaction',
            field=models.ManyToManyField(blank=True, to='transactions.Transactions'),
        ),
        migrations.AddField(
            model_name='clientpurse',
            name='queue',
            field=models.ManyToManyField(to='transactions.QueueClientTransactions'),
        ),
    ]
