# Generated by Django 3.2 on 2022-05-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20220517_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpurse',
            name='queue',
            field=models.ManyToManyField(blank=True, to='transactions.QueueClientTransactions', verbose_name='Очередь'),
        ),
    ]
