# Generated by Django 3.2 on 2022-05-17 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0005_auto_20220517_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientpurse',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clientpurse',
            name='username',
        ),
        migrations.AlterField(
            model_name='clientpurse',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
    ]
